name: continuous_deployment
on: 
  workflow_dispatch:

  # needs to use workflow name within the file
  # not the name of the file

  #also, just found at that you need to merge the code with main to be able to run the 
  #workflows properly in actions
  workflow_run: 
    workflows: 
      - continuous_integration 
      - continuous_training
    types: 
      - completed

  

jobs:
  cd_pipeline:
    name: continuous_deployment_job
    runs-on: self-hosted

    steps:
    - name: setup
      uses: actions/checkout@v4
    
    - name: building_docker_image # deploy to production(main)
      run: |
        echo "Starting the build."
        docker build . -t score_predictor
        echo "Building finished."

    - name: running_docker_image
      run: |
        echo "Attempting to deploy the image."
        docker run score_predictor
        docker ps
        echo "Image deployed."
