name: continuous_integration
on: 
  workflow_dispatch:
  push:
  

jobs:
  ci_pipeline: #job_1
    name: continuous_integration_job
    runs-on: ubuntu-latest

    steps:
    - name: setup
      uses: actions/checkout@v4
    
    - name: python_setup
      uses: actions/setup-python@v4
      with: 
        python_version: '3.9' 
    
    - name: installing_testing_libraries
      run: |
        pip install pytest pylint

    - name: unit_testing
      run: |
        echo "Unit testing code."
        pytest unit_test.py
        echo "Unit testing finished."

    - name: quality_testing
      run: |
        echo "Quality testing code."
        pylint model.py
        pylint flaskapp.py
        echo "Quality testing finished."

    - name: deployment # basically, starts off the 'deployment' workflow.
      run: |
        echo "Starts the 'Deployment' workflow."
       