name: continuous_monitoring
on:
  workflow_dispatch:
  workflow_run: 
    workflows: 
      - continuous_deployment
    types: 
      - success


jobs:
  cm_pipeline:
    name: continuous_monitoring_job
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/checkout@v4
    
    - name: monitoring_startup
      run: |
        echo "Monitoring startup."
    
    - name: retrain
      run: |
        echo "Runs the retraining code, if neccessary"
