name: continuous_training
on: 
  workflow_dispatch:
  schedule:
    cron: '0 21 * * *'
    #cron: '(minutes) (hours) () () (day)'
    #e.g 1: '30 6,18 * * 1,6' = runs the workflow at 6:30 and 18:30 on Monday and Saturday

#also, make it so it's trained based on trigger from other workflows



jobs:
  ct_pipeline:
    name: continuous_training_job
    runs-on: ubuntu-latest
    steps:
    - name: setup
      uses: actions/checkout@v4
    
    #acquire/preprocess data
    - name: data_preparation 
      run: | 
        echo "Get's data, and preprocesses it."

    #feature extract
    - name: feature_extraction
      run: |
        echo "Get's the needed features, if need be."
  
    #retrain
    - name: training_model
      run: |
        echo "Model retrained."

    #validate
    - name: model_validation #accuracy test
      run: |
        echo "Model performance checked."

    #deployment